### ISSUE TITLE
Use stateless components

### ISSUE THREAD

**Issue by neilff** [rangle/react-redux-seed#2]
React 0.14 offers stateless components, this feature should be used where it makes sense (there is a good argument that they can be used everywhere). 

At the least, I believe the Counter component should be a stateless component rather than extending React.Component.

**Comment by bertrandk** [comment]
I'm definitely in favour. Are there any objections to this? Any thoughts @rbrander?

**Comment by andrejkn** [comment]
@bertrandk @neilff @rbrander 
I've made an example of a stateless component
https://github.com/rangle/react-redux-seed/pull/9/

Will be closing this issue soon... :+1:

**Comment by neilff** [comment]
Everything is stateless now
